config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :markets
    resources :market_places
    resources :categories
    resources :packages
    resources :referral_fees
    resources :shipping_rates
    resources :calculations

    root to: 'markets#index'
  end

  root 'markets#index'

  resources :markets, only: %i[index show]

  resource :calculations, only: :create do
    resource :results, only: :show
  end

  resources :reports, only: :index
end

app/models/calculation.rb
# frozen_string_literal: true

class Calculation < ApplicationRecord
  has_secure_token

  def self.to_csv
    Calculations::Export.call(object: self)
  end
end

app/controllers/admin/calculations_controller.rb
# frozen_string_literal: true

module Admin
  class CalculationsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Calculation.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Calculation.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/calculations_controller.rb
# frozen_string_literal: true

class CalculationsController < ApplicationController
  after_action :set_result, only: :create

  def create
    @facade = Calculations::CreateFacade.new(info: params[:info])

    return redirect_back(@facade.error_redirect_params) unless @facade.result_valid?

    redirect_to calculations_results_path
  end

  private

  def set_result
    session[:last_result_token] = @facade.result_token if @facade.result_valid?
  end
end

app/views/admin/calculations/_collection.html.erb
<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/calculations/index.html.erb
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <%= link_to 'Export to CSV', reports_path(format: :csv), class: 'button' %>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <% if valid_action?(:new) && show_action?(:new, new_resource) %>
      <%= link_to(
        t(
          "administrate.actions.new_resource",
          name: page.resource_name.titleize.downcase
        ),
        [:new, namespace, page.resource_path],
        class: "button",
      )%>
    <% end %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter:  page,
    collection_field_name: resource_name,
    page:                  page,
    resources:             resources,
    table_title:           "page-title"
  ) %>

  <%= paginate resources %>
</section>